-- CRIANDO BANCO DE DADOS
CREATE DATABASE RH;
-- USANDO O BANCO DE DADOS
USE RH;
-- CRIANDO A TABELA
CREATE TABLE COLABORADORES(
	id int auto_increment,
	nome varchar (25),
	cpf varchar (11),
    salario int (255),
	primary key(id)
);
-- INSERINDO DADOS NA TABELA
INSERT INTO COLABORADORES(nome,cpf,salario) VALUES ("Paulo", "12345678910",2500);
INSERT INTO COLABORADORES(nome,cpf,salario) VALUES ("Amanda", "12354687956",2100);
INSERT INTO COLABORADORES(nome,cpf,salario) VALUES ("Fernando", "12546987524",3000);
INSERT INTO COLABORADORES(nome,cpf,salario) VALUES ("Edmilson", "1324678910",1800);
INSERT INTO COLABORADORES(nome,cpf,salario) VALUES ("Raimunda", "1223378910",1500);
-- ALTER TABLE COLABORADORES ADD COLUMN SALARIO INT; PRA ADD ATRIBUTO
-- DELETE FROM COLABORADORES; PRA DELETA TODA A TABELA (NAO FAÇA ISSO)(NECESSARIO DESATIVAR SAFE MODE)
-- SELECIONANDO DADOS ESPECIFICOS
SELECT * FROM COLABORADORES WHERE salario >= 2000;
SELECT * FROM COLABORADORES WHERE salario <= 2000;
-- ATUALIZANDO DADOS ESPECIFICOS
UPDATE COLABORADORES SET SALARIO = 1900 WHERE id = 5;
-- SELECIONANDO A TABELA TODA
SELECT * FROM COLABORADORES;